# Debugging overrides for attaching in VSCode. Not required for running
# in Visual Studio as these are generated automatically
version: '3.4'

services:

# Services 
  users.api:
    image: userapi:dev
    build:
      target: build
    volumes:
      - .\Services\Users\Users.API:/app
      - .:/src
      - $USERPROFILE\vsdbg\vs2017u5:/remote_debugger:rw
    entrypoint: dotnet /app/bin/Debug/net5.0/Users.Api.dll